### PR TITLE
Demonstrate successful compilation on arduino-esp32 master

### PR DESCRIPTION
**Pull request by xtrinch**

### CODE REVIEW

**Comment by chegewara** [comment]
Thanks for this PR, i will test it and merge.

**Comment by chegewara** [comment]
@xtrinch Can you create PR to `platformio` branch please?

**Comment by xtrinch** [comment]
Sure, can do, but that branch does not exist so I can't make a PR to that?

Also, I've updated it to include the files I've previously deleted and everything works fine except I wasn't able to figure out which of the new midi functions in master are equivalent to the old ones, so I've commented them out.

**Comment by chegewara** [comment]
I just created branch

**Comment by xtrinch** [comment]
Cool, thx, changed the base branch

**Pull request merged**
