### PR TITLE
Add sendString function

### PR DESCRIPTION
**Pull request by joelsernamoreno**
Hi!

I have added the sendString function, this allows you to send a text string.

Example: dev.sendString("Hello World Test sendString function");

### CODE REVIEW

**Comment by chegewara** [comment]
Thanks, but its better to use all 6 bytes in buffer sent to host, this way its possible to speed up up to 6 times, which is significant, just a bit more code required to add in that function.

**Comment by joelsernamoreno** [comment]
Hi!

Well, this is just an example. If you want you can modify it to work as you say

Thank you!

**Comment by chegewara** [comment]
Yes, thank you. I did not add similar function in first place to let users to do it in own code, but i can add it if there is request.

**Comment by joelsernamoreno** [comment]
Yes, this is fine for adding keyboard library functions

sendString
sendPress
sendRelease

It can also be interesting to be able to make scripts with this, for example:

sendPress(LEFT_MOD_GUI);
sendPress(KEY_R);
sendRelease();
sendString("notepad");
sendPress(KEY_RETURN);
sendRelease();
sendString("Hello World")

**Comment by chegewara** [comment]
Ok, i have implemented sendString() with concept i describbed, but i found issue that is way too complicated (still possible) to solve and not worth to do it. In that case i will merge your PR. Thanks.

**Comment by chegewara** [comment]
Added few more function according to your suggestion.

**Comment by joelsernamoreno** [comment]
Thank you, I will try this tomorrow

I am developing low cost devices with ESP32-S2, I will send you some of these when I finish the development

**Comment by chegewara** [comment]
> I am developing low cost devices with ESP32-S2, 

Thats great. If you have other ideas i can try to add to library.

**Comment by joelsernamoreno** [comment]
Yes, you can look at my github and find Evil Crow Cable, Evil Crow Keylogger, etc.

I am currently updating my devices to work with ESP32-S2 and be even cheaper 

I need to test your USB Disk, in the future it could be interesting to add SD Mass Storage

I will try sendPress and sendRelease tomorrow. I can also implement your library to be multi-layout

I have many ideas, I will inform you when I make more tests with this

**Comment by joelsernamoreno** [comment]
Hello!

One question: where can I find the modifiers and keys available?

I am using HID_KEY_LEFT_GUI and KEY_LEFT_GUI but they are not declared. How can I look at this?

**Comment by chegewara** [comment]
https://github.com/hathach/tinyusb/blob/master/src/class/hid/hid.h#L215

**Comment by joelsernamoreno** [comment]
Thank you

I am developing a code to use the keyboard through a web panel

I will give you access when I finish this and I do the documentation

**Comment by joelsernamoreno** [comment]
Hello!

I have given you access to my EvilCrow-Cable V2 repository

You can use some things from my code if you find them interesting

When the hardware is finished, I will send you a device and include you in the collaborators

At the moment I am using the EspTinyUSB library (fork) in the documentation. This way, if you update your library this does not affect the operation of my device 

If you have any doubt with my code, ask me :)

Thanks!

**Comment by joelsernamoreno** [comment]
Hi!

Check this for USB Host: https://github.com/sdima1357/esp32_usb_soft_host

**Comment by joelsernamoreno** [comment]
Hello!

I have seen that you have implemented some things for USB Host

Have you tried USB Host Keyboard for a keylogger?

**Comment by chegewara** [comment]
Hi
no, i didnt try to add HID host yet, but it should works as far as i could test with connected keyboard and mouse.

**Comment by joelsernamoreno** [comment]
Well, let me know if you ever try this. It might be fun to develop a very small hardware keylogger with ESP32-S2. Currently I have to use USB Host Max3421e, atmega32u4 and ESP8285. This is a very large PCB

https://github.com/joelsernamoreno/EvilCrow-Keylogger

**Comment by joelsernamoreno** [comment]
ESP32-pico*

**Comment by joelsernamoreno** [comment]
Hello!

Any progress with USB Host HID? I'm trying to implement this, but no luck yet 

Thanks

**Pull request merged**
